---
- hosts: webserver
  become: yes
  vars: 
    myvariables: [user1, user2, user3]
  tasks:
  - name: display myvariables
    debug:
       msg: "{{ item }}"
    with_items:
      - "{{ myvariables }}"   