---
- hosts: webserver
  become: yes
  vars: 
    myvar1: e1
    myvar2: shekhar
  tasks:
  - name:  display myvar1
    debug:
      msg: "{{myvar1}}"

  - name: display myvar2
    debug:
      msg: "{{myvar2}}"