---
- hosts: dbserver
  become: yes
  tasks:
  - include_tasks: main1.yml
  - include_tasks: main2.yml
  - include_tasks: main3.yml
  roles:  
   - {role: taskrole, when: ansible_os_family =="RedHat"}